### ISSUE TITLE
remove border around color masked images

### ISSUE THREAD

**Issue by tanmaypandey7** [abreheret/PixelAnnotationTool#31]
Hi, as referenced in https://github.com/abreheret/PixelAnnotationTool/issues/7, I am also experiencing this random noise around my images while saving them, which is leading to further problems. Using version 1.3.1
I will upload the images where this noise is occuring(look them up in new tab):
Uploading both original and masked images(my main use is of color mask, just uploading all the images so it may help find the problem):
A_103:
original image:
![a_103](https://user-images.githubusercontent.com/36691630/52845256-a6e72900-312c-11e9-855e-cc27d949341f.jpg)
color_mask:
![a_103_color_mask](https://user-images.githubusercontent.com/36691630/52845257-a77fbf80-312c-11e9-934e-61e616f3c0e1.png)
mask:
![a_103_mask](https://user-images.githubusercontent.com/36691630/52845252-a64e9280-312c-11e9-8e45-6535d1b6b356.png)
watershed_mask:
![a_103_watershed_mask](https://user-images.githubusercontent.com/36691630/52845254-a6e72900-312c-11e9-8ec8-eb1f1bf0fcd8.png)

A_104:
original image:
![a_104](https://user-images.githubusercontent.com/36691630/52845265-acdd0a00-312c-11e9-950b-c7bc8eec306d.jpg)
color_mask:
![a_104_color_mask](https://user-images.githubusercontent.com/36691630/52845268-ad75a080-312c-11e9-957e-ba9f0e6aaae8.png)
mask:
![a_104_mask](https://user-images.githubusercontent.com/36691630/52845261-ac447380-312c-11e9-8321-24486bcc1aac.png)
watershed_mask:
![a_104_watershed_mask](https://user-images.githubusercontent.com/36691630/52845262-ac447380-312c-11e9-9712-a0317efcbc5e.png)

A_106:
original image:
![a_106](https://user-images.githubusercontent.com/36691630/52845282-b49cae80-312c-11e9-8e21-c8ee06a1fada.jpg)
color_mask:
![a_106_color_mask](https://user-images.githubusercontent.com/36691630/52845283-b5354500-312c-11e9-8c55-de0d3eb5e2ab.png)
mask:
![a_106_mask](https://user-images.githubusercontent.com/36691630/52845284-b5354500-312c-11e9-872a-003e49e174d7.png)
watershed_mask:
![a_106_watershed_mask](https://user-images.githubusercontent.com/36691630/52845279-b49cae80-312c-11e9-8c3c-4098ca70bde7.png)
I can upload more images if required.

**Comment by abreheret** [comment]
There is no noise, strictly speaking. For the watershed to work it is necessary to have at least one different class in the pictures for the watershed to find the frontriere between the two classes. If you check the "keep border provide by the watershed" box then there will be white pixels on this boundary, however if your class is touching, then there will be no white pixel between these two classes.
For your case if the class with id 3 is green and class id 23 in red it gives a mask:
![image](https://user-images.githubusercontent.com/7152894/52852114-071fa000-3118-11e9-9d8f-fa0347af37af.png) 
As we can see the left and right side of the object search on a common border. That's why the result with the border gives white pixels on the rest of the border.
![image](https://user-images.githubusercontent.com/7152894/52852359-a2b11080-3118-11e9-84e9-561f0401c8d3.png)

With the new commit [ef64006] I updated the display correctly

**Comment by abreheret** [comment]
I make a new release v1.3.2 you can download here: 
https://github.com/abreheret/PixelAnnotationTool/releases/tag/v1.3.2

**Comment by tanmaypandey7** [comment]
Hello, I believe you understood the mask as in watershed border. That is not the problem. 
Please check the color mask in a new tab. It contains random pixels around the corners of the image which is leading to problems.
