### ISSUE TITLE
image zooming function is not friendly

### ISSUE THREAD

**Issue by mepleleo** [abreheret/PixelAnnotationTool#77]
The image zooming function is not friendly. In the current version(1.4.0), the region to be marked cannot be found after the image is enlarged by pressing Ctrl. For example, Photoshop zooms the image by the current position of the mouse, which is convenient to operate. I hope it can be improved. Thks

**Comment by daandres** [comment]
#74

**Comment by arbasli2** [comment]
I am using this software for annotating defects. Since we need a fine annotation, the image has to be zoomed in regularly. However constantly loosing the center point creates a big burden and greatly slows down the process. Please add this feature to the software. 
The pull request mentioned above is stalled and there is no progress in that direction.
Thank you.

**Comment by mepleleo** [comment]
————————————您好，来信已收到，谢谢。

**Comment by arbasli2** [comment]
In case someone is interested: I have forked this repo and merged the changes from BestRevRome (#74) regarding this feature to the latest commit of the main repo (as of today: 4920f8e). It compiles under windows too (tested with visual studio 17 2022, QT 5.15).

https://github.com/arbasli2/PixelAnnotationTool feature is added in commit : 
"02a25cb26206f8b9119fa1fa383c59a88b4aa61f"

**Comment by abreheret** [comment]
Nice, I will put a new release (1.5.0) soon which contains your changes.
